[package]
name = "rpdf"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[dependencies]
app_units = "0.7.1"
crossbeam = "0.7.1"
env_logger = "0.6.0"
euclid = "0.19.5"
failure = "0.1.5"
gleam = "0.6.8"
glutin = "0.19.0"
log = "0.4.6"
lopdf = "0.19.0"
structopt = "0.2.14"

[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "3c9bbeea72f5961592f0ee9400204f966235cf12"